alias vpn='/opt/cisco/anyconnect/bin/vpn'
alias vpnui='/opt/cisco/anyconnect/bin/vpnui'
alias prog='cd ~/Documents/Programs/'
alias tagger='ctags -R .'
alias config='/usr/bin/git --git-dir=/home/shreyansh/.cfg/ --work-tree=/home/shreyansh'
alias vv='cd $HOME/Documents/Research/Notes/ && nvim.appimage'
alias v='nvim.appimage'
alias vim='nvim.appimage'
